name: wedding-invitation

# API Service
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    source_dir: /api
    run_command: npm start
    build_command: npm install
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    health_check:
      http_path: /api/health

# Static Site (Frontend)
static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    source_dir: /
    output_dir: /
    index_document: wedding-invitation.html
    error_document: wedding-invitation.html
    routes:
      - path: /
    envs: []

# PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    cluster_name: wedding-rsvp-db
